<a href="https://colab.research.google.com/github/maryamshanab/Machine-learning-/blob/main/Library%20Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import torch

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

def problem_1():
    M = np.array([
        [4, -2, 7, 0],
        [1, 9, 3, -5],
        [8, 6, -1, 2]
    ])

    dimensions = M.shape

    m13 = M[0, 2]
    m24 = M[1, 3]
    m32 = M[2, 1]

    return dimensions, m13, m24, m32


print(problem_1())


def problem_2():
    A = np.array([
        [3, 5],
        [-1, 4]
    ])

    B = np.array([
        [0, -2],
        [7, 1]
    ])

    C = np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])

    addition = A + B
    subtraction = A - B

    can_add = A.shape == C.shape

    return addition, subtraction, can_add


addition, subtraction, can_add = problem_2()

print("A + B:")
print(addition)

print("A - B:")
print(subtraction)

print("Can A + C?", can_add)


def problem_3():
    X = np.array([
        [2, -1],
        [3, 0]
    ])

    Y = np.array([
        [1, 4],
        [-2, 5]
    ])

    scalar = 3 * X

    element_wise = X * Y

    X_torch = torch.tensor(X, dtype=torch.float32)
    Y_torch = torch.tensor(Y, dtype=torch.float32)

    matrix_product = torch.matmul(X_torch, Y_torch)

    return scalar, element_wise, matrix_product


scalar, element_wise, matrix_product = problem_3()

print("3X:")
print(scalar)

print("\nElement-wise:")
print(element_wise)

print("\nMatrix multiplication:")
print(matrix_product)



def problem_4():
    K = torch.tensor([
        [5, 2],
        [3, 4]
    ], dtype=torch.float32)

    transpose = K.T

    determinant = torch.linalg.det(K)

    inverse = torch.linalg.inv(K)

    return transpose, determinant, inverse


transpose, determinant, inverse = problem_4()

print("Transpose:")
print(transpose)

print("\nDeterminant:")
print(determinant)

print("\nInverse:")
print(inverse)


def problem_5():
    A = torch.tensor([
        [2, 3],
        [4, -1]
    ], dtype=torch.float32)

    B = torch.tensor([
        [13],
        [5]
    ], dtype=torch.float32)

    X = torch.linalg.solve(A, B)

    x = X[0].item()
    y = X[1].item()

    return A, B, X, x, y


A, B, X, x, y = problem_5()

print("A:")
print(A)

print("\nB:")
print(B)

print("\nX:")
print(X)

print("\nx =", x)
print("y =", y)


def problem_6():
    data = pd.Series([
        120, 150, 130, 180,
        150, 200, 110, 160
    ])

    mean = data.mean()

    median = data.median()

    mode = data.mode()

    return mean, median, mode


mean, median, mode = problem_6()

print("Mean:", mean)
print("Median:", median)
print("Mode:")
print(mode)


def problem_7():
    data = pd.Series([2, 4, 6, 8, 10])

    sample_std = data.std()

    q1 = data.quantile(0.25)
    q3 = data.quantile(0.75)

    iqr = q3 - q1

    return sample_std, q1, q3, iqr


std, q1, q3, iqr = problem_7()

print("Sample Standard Deviation:", std)
print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)


def problem_8():
    data = pd.DataFrame({
        "Area": [1200, np.nan, 1800],
        "Bedrooms": [2, 3, 4],
        "Price": [200000, 250000, 350000]
    })

    imputer = SimpleImputer(strategy="mean")

    data["Area"] = imputer.fit_transform(
        data[["Area"]]
    )

    scaler = MinMaxScaler()

    data["Area_Scaled"] = scaler.fit_transform(
        data[["Area"]]
    )

    return data


result = problem_8()

print(result)



def problem_9():
    X = np.arange(100).reshape(-1, 1)

    X_train, X_test = train_test_split(
        X,
        test_size=0.2,
        random_state=42
    )

    scaler = MinMaxScaler()

    X_train_scaled = scaler.fit_transform(X_train)

    X_test_scaled = scaler.transform(X_test)

    return X_train, X_test, X_train_scaled, X_test_scaled


X_train, X_test, X_train_scaled, X_test_scaled = problem_9()

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

def predict_car_price(age):
    price = -2000 * age + 25000
    return price


def calculate_residual(actual, predicted):
    residual = actual - predicted
    return residual



def problem_9():
    data = pd.DataFrame({
        "Feature": np.arange(100)
    })

    X_train, X_test = train_test_split(
        data,
        test_size=0.2,
        random_state=42
    )

    scaler = MinMaxScaler()

    X_train_scaled = scaler.fit_transform(X_train)

    X_test_scaled = scaler.transform(X_test)

    return X_train, X_test, X_train_scaled, X_test_scaled


X_train, X_test, X_train_scaled, X_test_scaled = problem_9()

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))


predicted, residual = problem_10()

print("Predicted Price:", predicted)
print("Residual:", residual)

((3, 4), np.int64(7), np.int64(-5), np.int64(6))
A + B:
[[3 3]
 [6 5]]
A - B:
[[ 3  7]
 [-8  3]]
Can A + C? False
3X:
[[ 6 -3]
 [ 9  0]]

Element-wise:
[[ 2 -4]
 [-6  0]]

Matrix multiplication:
tensor([[ 4.,  3.],
        [ 3., 12.]])
Transpose:
tensor([[5., 3.],
        [2., 4.]])

Determinant:
tensor(14.)

Inverse:
tensor([[ 0.2857, -0.1429],
        [-0.2143,  0.3571]])
A:
tensor([[ 2.,  3.],
        [ 4., -1.]])

B:
tensor([[13.],
        [ 5.]])

X:
tensor([[2.0000],
        [3.0000]])

x = 2.0
y = 3.000000238418579
Mean: 150.0
Median: 150.0
Mode:
0    150
dtype: int64
Sample Standard Deviation: 3.1622776601683795
Q1: 4.0
Q3: 8.0
IQR: 4.0
     Area  Bedrooms   Price  Area_Scaled
0  1200.0         2  200000          0.0
1  1500.0         3  250000          0.5
2  1800.0         4  350000          1.0
Training samples: 80
Testing samples: 20
Training samples: 80
Testing samples: 20
Predicted Price: 17000
Residual: -1000
