In [1]:
import numpy as np
import pandas as pd

A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

B = np.array([[6],
              [-11],
              [-3]])

print("--- Matrix A Shape & Dimensions ---")
print("Shape of A:", A.shape)  # (3, 3)
print("Dimensions:", A.ndim)  # 2D

# B. Matrix Indexing (الوصول للعناصر)
print("\nElement at Row 2, Column 3 (Index 1, 2):", A[1, 2])

# C. Matrix Multiplication (ضرب المصفوفات)
# ضرب عنصر بـ عنصر (Element-wise)
print("\nElement-wise A * A:\n", A * A)

# الضرب الرياضي (Dot Product)
C = np.dot(A, A)  # أو A @ A
print("\nMatrix Multiplication (A @ A):\n", C)


#%% ==========================================
# 2. SOLVING SYSTEM OF LINEAR EQUATIONS
# ==========================================
# لنفترض أن لدينا النظام الخطي التالي:
# 2x + 1y - 1z = 6
# -3x - 1y + 2z = -11
# -2x + 1y + 2z = -3

print("\n--- Solving Linear Equations (A * X = B) ---")

# الطريقة الأولى: استخدام المعكوس (A_inv * B)
A_inv = np.linalg.inv(A)
X_inv = np.dot(A_inv, B)
print("Solution using Inverse (x, y, z):\n", X_inv)

# الطريقة الثانية: المباشرة والأكثر دقة برمجياً (np.linalg.solve)
X_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve (x, y, z):\n", X_solve)


#%% ==========================================
# 3. PANDAS & DATA FRAME INTEGRATION
# ==========================================

# تحويل البيانات والمصفوفات إلى جدول Pandas DataFrame
# تخيل أن لدينا بيانات 5 طلاب ومجموعات درجاتهم في 3 مواد
data_matrix = np.array([
    [85, 90, 78],
    [60, 70, 65],
    [92, 95, 98],
    [75, 80, 70],
    [50, 55, 60]
])

student_names = ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
subjects = ['Math_LinearAlgebra', 'Statistics', 'Python_Programming']

# A. إنشاء DataFrame من مصفوفة NumPy
df = pd.DataFrame(data=data_matrix, index=student_names, columns=subjects)

print("\n--- Pandas DataFrame ---")
print(df)

# B. ربط مفاهيم Matrix Indexing مع Pandas (loc & iloc)
print("\nCharlie's Grades (using loc):")
print(df.loc['Charlie'])

print("\nStatistics Grade for Bob (Row Index 1, Col Index 1 using iloc):")
print(df.iloc[1, 1])

# C. العمليات الإحصائية على المصفوفة داخل Pandas
print("\n--- Summary Statistics (Mean per Subject) ---")
print(df.mean(axis=0))  # axis=0 يحسب المتوسط لكل عمود

# D. إضافة عمود جديد حسابي (إجمالي الدرجات باختبار المصفوفات)
df['Total_Score'] = df.sum(axis=1)
print("\n--- Final Table with Total Scores ---")
print(df)

--- Matrix A Shape & Dimensions ---
Shape of A: (3, 3)
Dimensions: 2

Element at Row 2, Column 3 (Index 1, 2): 2

Element-wise A * A:
 [[4 1 1]
 [9 1 4]
 [4 1 4]]

Matrix Multiplication (A @ A):
 [[  3   0  -2]
 [ -7   0   5]
 [-11  -1   8]]

--- Solving Linear Equations (A * X = B) ---
Solution using Inverse (x, y, z):
 [[ -6.]
 [  7.]
 [-11.]]

Solution using np.linalg.solve (x, y, z):
 [[ -6.]
 [  7.]
 [-11.]]

--- Pandas DataFrame ---
         Math_LinearAlgebra  Statistics  Python_Programming
Alice                    85          90                  78
Bob                      60          70                  65
Charlie                  92          95                  98
David                    75          80                  70
Eva                      50          55                  60

Charlie's Grades (using loc):
Math_LinearAlgebra    92
Statistics            95
Python_Programming    98
Name: Charlie, dtype: int64

Statistics Grade for Bob (Row Index 1, Col Index 1 using iloc)